# FZF color scheme generated by wallust
# This file is sourced by zsh to theme fzf

export FZF_DEFAULT_OPTS="
  --height 40%
  --layout=reverse
  --border
  --inline-info
  --color=fg:{{foreground}}
  --color=bg:{{background}}
  --color=hl:{{color5}}
  --color=fg+:{{foreground}}
  --color=bg+:{{color8}}
  --color=hl+:{{color13}}
  --color=info:{{color6}}
  --color=prompt:{{color2}}
  --color=pointer:{{color5}}
  --color=marker:{{color3}}
  --color=spinner:{{color6}}
  --color=header:{{color4}}
  --color=border:{{color8}}
"
