-- Wallust colorscheme for Neovim
-- Generated by wallust from color palette

-- Clear existing highlights and setup
if vim.g.colors_name then
  vim.cmd("highlight clear")
end
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

vim.o.termguicolors = true
vim.g.colors_name = "wallust"

-- Colors from wallust
local c = {
  none = "NONE",
  bg = "{{background}}",
  fg = "{{foreground}}",
  cursor = "{{cursor}}",

  -- ANSI colors
  black = "{{color0}}",
  red = "{{color1}}",
  green = "{{color2}}",
  yellow = "{{color3}}",
  blue = "{{color4}}",
  magenta = "{{color5}}",
  cyan = "{{color6}}",
  white = "{{color7}}",

  bright_black = "{{color8}}",
  bright_red = "{{color9}}",
  bright_green = "{{color10}}",
  bright_yellow = "{{color11}}",
  bright_blue = "{{color12}}",
  bright_magenta = "{{color13}}",
  bright_cyan = "{{color14}}",
  bright_white = "{{color15}}",
}

-- Helper to lighten/darken colors (simple implementation)
local function blend(color, amount)
  -- Simple alpha blend with background
  -- For proper blending, you'd use a color manipulation library
  return color
end

-- Semantic color assignments
local syntax = {
  comment = c.bright_black,
  constant = c.yellow,
  string = c.green,
  character = c.yellow,
  number = c.magenta,
  boolean = c.magenta,
  float = c.magenta,
  identifier = c.blue,
  func = c.green,
  statement = c.red,
  conditional = c.red,
  loop = c.red,
  keyword = c.red,
  operator = c.fg,
  exception = c.red,
  preproc = c.magenta,
  include = c.magenta,
  define = c.magenta,
  type = c.cyan,
  structure = c.cyan,
  special = c.magenta,
  error = c.red,
  warning = c.yellow,
  info = c.cyan,
  hint = c.bright_black,
}

local ui = {
  selection = c.bright_black,  -- Use contrasting background for selections
  menu_selection = c.blue,
  visual = c.bright_black,  -- Use contrasting background for visual mode
  cursorline = c.bright_black,  -- Use contrasting background for cursor line
  pmenu = c.bright_black,  -- Use contrasting background for popup menus
  float = c.bright_black,  -- Use contrasting background for floating windows
  border = c.bright_black,
  diff_add = c.green,
  diff_change = c.yellow,
  diff_delete = c.red,
  diff_text = c.blue,
}

-- Set terminal colors for :terminal
vim.g.terminal_color_0 = c.black
vim.g.terminal_color_1 = c.red
vim.g.terminal_color_2 = c.green
vim.g.terminal_color_3 = c.yellow
vim.g.terminal_color_4 = c.blue
vim.g.terminal_color_5 = c.magenta
vim.g.terminal_color_6 = c.cyan
vim.g.terminal_color_7 = c.white
vim.g.terminal_color_8 = c.bright_black
vim.g.terminal_color_9 = c.bright_red
vim.g.terminal_color_10 = c.bright_green
vim.g.terminal_color_11 = c.bright_yellow
vim.g.terminal_color_12 = c.bright_blue
vim.g.terminal_color_13 = c.bright_magenta
vim.g.terminal_color_14 = c.bright_cyan
vim.g.terminal_color_15 = c.bright_white

-- Highlight groups
local highlights = {
  -- Base groups
  Normal = { fg = c.fg, bg = c.bg },
  NormalFloat = { fg = c.fg, bg = ui.float },
  NormalNC = { fg = c.fg, bg = c.bg },

  -- Cursor
  Cursor = { fg = c.bg, bg = c.cursor },
  CursorLine = { bg = ui.cursorline },
  CursorColumn = { bg = ui.cursorline },
  ColorColumn = { bg = ui.cursorline },
  CursorLineNr = { fg = c.fg, bold = true },

  -- Line numbers
  LineNr = { fg = c.bright_black },
  SignColumn = { fg = c.bright_black },

  -- Folds
  Folded = { fg = c.bright_black, bg = c.black },
  FoldColumn = { fg = c.bright_black },

  -- Statusline
  StatusLine = { fg = c.fg, bg = c.black },
  StatusLineNC = { fg = c.bright_black, bg = c.black },

  -- Tabline
  TabLine = { fg = c.bright_black, bg = c.black },
  TabLineFill = { bg = c.black },
  TabLineSel = { fg = c.fg, bg = c.bg },

  -- Window
  VertSplit = { fg = ui.border },
  WinSeparator = { fg = ui.border },

  -- Search
  Search = { fg = c.bg, bg = c.yellow },
  IncSearch = { fg = c.bg, bg = c.yellow },
  CurSearch = { fg = c.bg, bg = c.yellow },

  -- Visual
  Visual = { bg = ui.visual },
  VisualNOS = { bg = ui.visual },

  -- Pmenu (popup menu)
  Pmenu = { fg = c.fg, bg = ui.pmenu },
  PmenuSel = { fg = c.bg, bg = ui.menu_selection, bold = true },
  PmenuSbar = { bg = ui.pmenu },
  PmenuThumb = { bg = c.bright_black },

  -- Messages
  ErrorMsg = { fg = syntax.error },
  WarningMsg = { fg = syntax.warning },
  ModeMsg = { fg = c.fg },
  MoreMsg = { fg = syntax.info },
  Question = { fg = syntax.info },

  -- Diff
  DiffAdd = { bg = ui.diff_add, fg = c.bg },
  DiffChange = { bg = ui.diff_change, fg = c.bg },
  DiffDelete = { bg = ui.diff_delete, fg = c.bg },
  DiffText = { bg = ui.diff_text, fg = c.bg },

  -- Spell
  SpellBad = { sp = syntax.error, undercurl = true },
  SpellCap = { sp = syntax.warning, undercurl = true },
  SpellLocal = { sp = syntax.info, undercurl = true },
  SpellRare = { sp = syntax.hint, undercurl = true },

  -- Syntax groups
  Comment = { fg = syntax.comment, italic = true },
  Constant = { fg = syntax.constant },
  String = { fg = syntax.string },
  Character = { fg = syntax.character },
  Number = { fg = syntax.number },
  Boolean = { fg = syntax.boolean },
  Float = { fg = syntax.float },
  Identifier = { fg = syntax.identifier },
  Function = { fg = syntax.func },
  Statement = { fg = syntax.statement },
  Conditional = { fg = syntax.conditional },
  Repeat = { fg = syntax.loop },
  Label = { fg = syntax.statement },
  Operator = { fg = syntax.operator },
  Keyword = { fg = syntax.keyword },
  Exception = { fg = syntax.exception },
  PreProc = { fg = syntax.preproc },
  Include = { fg = syntax.include },
  Define = { fg = syntax.define },
  Macro = { fg = syntax.define },
  PreCondit = { fg = syntax.preproc },
  Type = { fg = syntax.type },
  StorageClass = { fg = syntax.type },
  Structure = { fg = syntax.structure },
  Typedef = { fg = syntax.type },
  Special = { fg = syntax.special },
  SpecialChar = { fg = syntax.special },
  Tag = { fg = syntax.special },
  Delimiter = { fg = c.fg },
  SpecialComment = { fg = syntax.comment },
  Debug = { fg = syntax.error },
  Underlined = { underline = true },
  Ignore = { fg = c.bright_black },
  Error = { fg = syntax.error },
  Todo = { fg = syntax.warning, bold = true },

  -- Treesitter groups
  ["@variable"] = { fg = c.fg },
  ["@variable.builtin"] = { fg = syntax.keyword },
  ["@variable.parameter"] = { fg = syntax.identifier },
  ["@variable.member"] = { fg = syntax.identifier },
  ["@constant"] = { fg = syntax.constant },
  ["@constant.builtin"] = { fg = syntax.constant },
  ["@module"] = { fg = syntax.type },
  ["@string"] = { fg = syntax.string },
  ["@character"] = { fg = syntax.character },
  ["@number"] = { fg = syntax.number },
  ["@boolean"] = { fg = syntax.boolean },
  ["@float"] = { fg = syntax.float },
  ["@function"] = { fg = syntax.func },
  ["@function.builtin"] = { fg = syntax.func },
  ["@function.macro"] = { fg = syntax.define },
  ["@function.method"] = { fg = syntax.func },
  ["@constructor"] = { fg = syntax.type },
  ["@keyword"] = { fg = syntax.keyword },
  ["@keyword.function"] = { fg = syntax.keyword },
  ["@keyword.operator"] = { fg = syntax.operator },
  ["@keyword.return"] = { fg = syntax.keyword },
  ["@conditional"] = { fg = syntax.conditional },
  ["@repeat"] = { fg = syntax.loop },
  ["@label"] = { fg = syntax.statement },
  ["@operator"] = { fg = syntax.operator },
  ["@exception"] = { fg = syntax.exception },
  ["@type"] = { fg = syntax.type },
  ["@type.builtin"] = { fg = syntax.type },
  ["@attribute"] = { fg = syntax.preproc },
  ["@property"] = { fg = syntax.identifier },
  ["@comment"] = { link = "Comment" },
  ["@punctuation.delimiter"] = { fg = c.fg },
  ["@punctuation.bracket"] = { fg = c.fg },
  ["@punctuation.special"] = { fg = syntax.special },

  -- LSP semantic tokens
  ["@lsp.type.class"] = { fg = syntax.type },
  ["@lsp.type.decorator"] = { fg = syntax.preproc },
  ["@lsp.type.enum"] = { fg = syntax.type },
  ["@lsp.type.enumMember"] = { fg = syntax.constant },
  ["@lsp.type.function"] = { fg = syntax.func },
  ["@lsp.type.interface"] = { fg = syntax.type },
  ["@lsp.type.macro"] = { fg = syntax.define },
  ["@lsp.type.method"] = { fg = syntax.func },
  ["@lsp.type.namespace"] = { fg = syntax.type },
  ["@lsp.type.parameter"] = { fg = syntax.identifier },
  ["@lsp.type.property"] = { fg = syntax.identifier },
  ["@lsp.type.struct"] = { fg = syntax.type },
  ["@lsp.type.type"] = { fg = syntax.type },
  ["@lsp.type.typeParameter"] = { fg = syntax.type },
  ["@lsp.type.variable"] = { fg = c.fg },

  -- Diagnostic
  DiagnosticError = { fg = syntax.error },
  DiagnosticWarn = { fg = syntax.warning },
  DiagnosticInfo = { fg = syntax.info },
  DiagnosticHint = { fg = syntax.hint },
  DiagnosticUnderlineError = { sp = syntax.error, undercurl = true },
  DiagnosticUnderlineWarn = { sp = syntax.warning, undercurl = true },
  DiagnosticUnderlineInfo = { sp = syntax.info, undercurl = true },
  DiagnosticUnderlineHint = { sp = syntax.hint, undercurl = true },

  -- Git signs
  GitSignsAdd = { fg = ui.diff_add },
  GitSignsChange = { fg = ui.diff_change },
  GitSignsDelete = { fg = ui.diff_delete },

  -- Dashboard (Snacks.nvim)
  SnacksDashboardHeader = { fg = c.cyan },
  SnacksDashboardFooter = { fg = c.cyan },
  SnacksDashboardSpecial = { fg = c.cyan },
  SnacksDashboardKey = { fg = c.yellow },
  SnacksDashboardDesc = { fg = c.fg },
  SnacksDashboardIcon = { fg = c.blue },
  SnacksDashboardTitle = { fg = c.magenta, bold = true },

  -- Alpha.nvim (alternative dashboard)
  AlphaHeader = { fg = c.cyan },
  AlphaButtons = { fg = c.blue },
  AlphaShortcut = { fg = c.yellow },
  AlphaFooter = { fg = c.cyan, italic = true },

  -- Markdown / Markup (Treesitter)
  ["@markup.heading"] = { fg = c.blue, bold = true },
  ["@markup.heading.1"] = { fg = c.red, bold = true },
  ["@markup.heading.2"] = { fg = c.yellow, bold = true },
  ["@markup.heading.3"] = { fg = c.green, bold = true },
  ["@markup.heading.4"] = { fg = c.cyan, bold = true },
  ["@markup.heading.5"] = { fg = c.blue, bold = true },
  ["@markup.heading.6"] = { fg = c.magenta, bold = true },
  ["@markup.strong"] = { fg = c.fg, bold = true },
  ["@markup.italic"] = { fg = c.fg, italic = true },
  ["@markup.strikethrough"] = { fg = c.bright_black, strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.link"] = { fg = c.cyan, underline = true },
  ["@markup.link.label"] = { fg = c.blue },
  ["@markup.link.url"] = { fg = c.cyan, underline = true },
  ["@markup.raw"] = { fg = c.green },
  ["@markup.raw.block"] = { fg = c.green },  -- No background for better readability
  ["@markup.quote"] = { fg = c.bright_black, italic = true },
  ["@markup.list"] = { fg = c.magenta },
  ["@markup.list.checked"] = { fg = c.green },
  ["@markup.list.unchecked"] = { fg = c.yellow },

  -- Markdown legacy (for older treesitter versions)
  ["@text.title"] = { link = "@markup.heading" },
  ["@text.strong"] = { link = "@markup.strong" },
  ["@text.emphasis"] = { link = "@markup.italic" },
  ["@text.underline"] = { link = "@markup.underline" },
  ["@text.strike"] = { link = "@markup.strikethrough" },
  ["@text.uri"] = { link = "@markup.link.url" },
  ["@text.literal"] = { link = "@markup.raw" },
  ["@text.quote"] = { link = "@markup.quote" },

  -- Render-markdown plugin highlights
  RenderMarkdownCode = { bg = c.black },  -- Subtle background for code blocks
  RenderMarkdownCodeInline = { fg = c.green, italic = true },
  RenderMarkdownH1Bg = { bg = c.black },
  RenderMarkdownH2Bg = { bg = c.black },
  RenderMarkdownH3Bg = { bg = c.black },
  RenderMarkdownH4Bg = { bg = c.black },
  RenderMarkdownH5Bg = { bg = c.black },
  RenderMarkdownH6Bg = { bg = c.black },

  -- Telescope fuzzy finder (kept for compatibility if user switches back)
  TelescopeBorder = { fg = ui.border, bg = ui.float },
  TelescopeNormal = { fg = c.fg, bg = ui.float },
  TelescopePromptNormal = { fg = c.fg, bg = ui.float },
  TelescopePromptBorder = { fg = ui.border, bg = ui.float },
  TelescopePromptTitle = { fg = c.bg, bg = c.blue, bold = true },
  TelescopePreviewTitle = { fg = c.bg, bg = c.green, bold = true },
  TelescopeResultsTitle = { fg = c.bg, bg = c.magenta, bold = true },
  TelescopeSelection = { fg = c.fg, bg = ui.selection, bold = true },
  TelescopeSelectionCaret = { fg = c.blue, bg = ui.selection },
  TelescopeMultiSelection = { fg = c.magenta, bg = ui.selection },
  TelescopeMatching = { fg = c.yellow, bold = true },

  -- Snacks.nvim Picker (fuzzy finder - replaces Telescope in AstroNvim v5)
  SnacksPickerBorder = { fg = ui.border, bg = ui.float },
  SnacksPicker = { fg = c.fg, bg = ui.float },
  SnacksPickerPreviewBorder = { fg = ui.border, bg = ui.float },
  SnacksPickerPreview = { fg = c.fg, bg = ui.float },
  SnacksPickerPreviewTitle = { fg = c.bg, bg = c.green, bold = true },
  SnacksPickerBoxBorder = { fg = ui.border, bg = ui.float },
  SnacksPickerInputBorder = { fg = ui.border, bg = ui.float },
  SnacksPickerInputSearch = { fg = c.fg, bg = ui.float },
  SnacksPickerListBorder = { fg = ui.border, bg = ui.float },
  SnacksPickerList = { fg = c.fg, bg = ui.float },
  SnacksPickerListTitle = { fg = c.bg, bg = c.blue, bold = true },
}

-- Apply all highlights
for group, settings in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, settings)
end
